### PR TITLE
Update to Support ExoPlayer 1.5.2

### PR DESCRIPTION
**Pull request by anggras**
* Updates support for ExoPlayer 1.5.x (current latest is 1.5.2 https://github.com/google/ExoPlayer/commit/97abb7abf764a745a0bdc7aef9a09a837bf1b28d )
* Includes compiled ExoPlayer 1.5.2 library
* Adds support for playing Ads when the overlay play button it touched
* Solves https://github.com/googleads/google-media-framework-android/issues/66, https://github.com/googleads/google-media-framework-android/issues/62, and https://github.com/googleads/google-media-framework-android/issues/51

### CODE REVIEW

**Comment by ypavlotsky** [comment]
Hi anggras,

Thanks for submitting the pull request. Please take a look at the CONTRIBUTING.md doc and fill out our one-page Contributor License Agreement form. We unfortunately can't accept any code changes without it, but it's a really quick process.

Other than that, we don't need the JAR file; I'll update that separately. Thanks again,

Yury
IMA SDK Team

**Comment by anggras** [comment]
Noted. We've signed and submitted the CLA on Nov 3, but have not received any reply yet.

**Comment by ypavlotsky** [comment]
Is it possible that you signed the CLA with a different email address from the one you use for GitHub? You can check the status of your CLA here: https://cla.developers.google.com/clas.

**Comment by anggras** [comment]
Alright, the one we signed on Nov 3 was the Corporate CLA. Anyway, I've signed as individual just now so all should be good now :)

**Comment by ypavlotsky** [comment]
Great, looks good now :-). 

Couple of things -- could you flatten your commits into one commit? And could you also remove the ExoPlayer JAR file? Thanks again.

**Comment by anggras** [comment]
Replaced with https://github.com/googleads/google-media-framework-android/pull/69

**Pull request closed without merging**
