### PR TITLE
support Exoplayer 1.5.5

### PR DESCRIPTION
**Pull request by giladna**
Update framework to work with Exoplayer jar v1.5.5
Add DASH Google glass stream

### CODE REVIEW

**Comment by ypavlotsky** [comment]
Hi Gilad,

Please sign our Contributor License Agreement (CLA) before sending pull requests. For any code changes to be accepted, the CLA must be signed. It's a quick process, we promise!

We have a [simple click-through form.](http://code.google.com/legal/individual-cla-v1.0.html)

Thanks!

**Comment by giladna** [comment]
done

**Comment by giladna** [comment]
Hi 
I'v already signed
I work at Katura LTD gilad.nadav@kaltura.com
github: is giladna

**Comment by ypavlotsky** [comment]
Sorry about the spam there, Gilad, I'd enabled the bot to auto-check and replied when it didn't seem to be retroactively working, but of course that caused it to work :-). Thanks again for the pull request, I'll look it over.

**Comment by ypavlotsky** [comment]
I've moved the ExoPlayer JAR out of the repo, could you flatten your commits and submit another pull request without the JAR, including ExoPlayer 1.5.5 from jCenter? Thanks.

**Comment by zhoul-HS** [comment]
@ypavlotsky I've sent a PR #88 with ExoPlayer 1.5.6

**Comment by sewasewa777** [comment]
H

**Comment by sassynanatena** [comment]
I never subscribed to this

**Pull request closed without merging**
